version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - MyNameIsMikeGreen
  ignore:
  - dependency-name: testcontainers[postgres]
    versions:
    - 3.4.0
