services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=docker_db
      - POSTGRES_PASSWORD=docker_db_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_DATABASE=docker_db
      - DB_USER=postgres
      - DB_PASSWORD=docker_db_password
      - DEBUG=True
      - SECRET_KEY=testkey
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "./reset-database.sh && ./run.sh"
