services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=./platypus.db
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "./reset-database.sh && ./run.sh"
