# Generated by Django 3.1.3 on 2021-01-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='pub_date',
            new_name='published_date',
        ),
    ]
