# Generated by Django 3.2 on 2021-10-20 21:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20211020_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=256), blank=True, default=list, size=None),
        ),
        migrations.DeleteModel(
            name='RecipeImage',
        ),
    ]
