# Generated by Django 3.2 on 2021-10-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20211020_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='images',
            new_name='image_urls',
        ),
    ]
