CREATE TABLE recipes (
    recipe_id INT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(128),
    ingredients VARCHAR(512),
    method VARCHAR(8192)
);

INSERT INTO recipes (title, method) VALUES ('This is my title.', 'This is my method.');
