# Generated by Django 4.1.5 on 2023-01-26 16:39

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('ingredients', recipes.models.PlatypusList(models.CharField(max_length=128), max_length=128, size=None)),
                ('method', recipes.models.PlatypusList(models.CharField(max_length=1024), max_length=1024, size=None)),
                ('category', models.CharField(default='UNCATEGORISED', max_length=32)),
                ('published_date', models.DateField(auto_now=True)),
                ('final', models.BooleanField(default=True)),
                ('tags', recipes.models.PlatypusList(models.CharField(max_length=128), blank=True, default=list, max_length=128, size=None)),
                ('image_urls', recipes.models.PlatypusList(models.URLField(max_length=256), blank=True, default=list, max_length=256, size=None)),
            ],
        ),
    ]
