# Generated by Django 2.2.13 on 2020-07-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('UNCATEGORISED', 'Uncategorised'), ('MAINS', 'Mains'), ('DESSERTS', 'Desserts'), ('SNACKS', 'Snacks')], default='UNCATEGORISED', max_length=32),
        ),
    ]
