# Generated by Django 3.0.7 on 2020-09-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20200731_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='UNCATEGORISED', max_length=32),
        ),
    ]
